[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "link-args=-Wl,/OPT:ICF,/OPT:REF",
]

[build]
rustflags = ["-C", "target-feature=+crt-static"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
